# Generated by Django 4.0.3 on 2022-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit_app', '0002_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('Email', models.EmailField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
