# Generated by Django 4.0.3 on 2022-03-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reddit_app', '0003_comentario_delete_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
